config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "weather#index"
  post "weather/show", to: "weather#show"
  get "weather/show", to: redirect('/')
end

app/models/address.rb
class Address
    attr_accessor :street, :city, :state, :zip
    attr_reader :errors

  def initialize(street:, city:, state:, zip:)
    @street = street
    @city = city
    @state = state
    @zip = zip
    @errors = []
  end

  def valid?
    @errors = []
    validate_street
    validate_city
    validate_state
    validate_zip
    errors.empty?
  end

  def validate_street
    if street.nil? || street.empty?
      @errors << "Street is required."
    end
  end

  def validate_city
    if city.nil? || city.empty?
      @errors << "City is required."
    end
  end

  def validate_state
    if state.nil? || state.length != 2
      @errors << "State must be 2 characters long."
    end
  end

  def validate_zip
    if zip.nil? || !zip.match?(/\A\d{5}(-\d{4})?\z/)
      @errors << "Zip must be a valid US zip code."
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
    def index
    end

    def show
        address_data = {
            street: params[:street],
            city: params[:city],
            state: params[:state],
            zip: params[:zip],
        }
        address = Address.new(**address_data)

        if address.zip
            @cached = true
            @weather_data = Rails.cache.read("weather_#{address.zip}")
            weather = WeatherService.new(address)
            
            unless @weather_data
                @cached = false
                @weather_data = weather.fetch
                Rails.cache.write("weather_#{address.zip}", @weather_data, expires_in: 30.minutes)
            end
            
            if @weather_data
                @address = address
                @highs_and_lows = weather.extract_with_highs_and_lows(@weather_data)
                render :show
            else
                flash[:error] = "Weather data could not be retrieved."
                redirect_to root_path
            end
        else
            flash[:error] = "Invalid address. Please try again."
            redirect_to root_path
        end
    end

    private

end

app/helpers/application_helper.rb
module ApplicationHelper
    def render_flash_messages
        flash.map do |type, message|
            tag.div message, 
              class: [
                {
                   notice: 'is-success',
                   alert: 'is-danger',
                   error: 'is-danger'
                }.fetch(type.to_sym, type.to_s), 
                "notification", 
                "is-light", 
                "text-center"
              ]
        end.join.html_safe
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWeather</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render_flash_messages %>
    <%= yield %>
  </body>
</html>

app/views/weather/index.html.erb
<h1>Weather</h1>
<%= form_with url: weather_show_path, method: :post, local: true do %>
    Enter address:
	<div>
		<div><label for="street">Street:</label><%= text_field_tag :street %></div>
		<div><label for="city">City:</label><%= text_field_tag :city %></div>
		<div><label for="state">State:</label><%= text_field_tag :state %></div>
		<div><label for="zip">Zip:</label><%= text_field_tag :zip %></div>
	</div>

	<div>
		<%= submit_tag "Get Weather" %>
	</div>
<% end %>

app/views/weather/show.html.erb
<div class="container">
	<h3>Weather for <%= @address.street %></h3>

	<table class="highlight centered">
		<thead>
			<tr>
				<th>Date</th>
				<th>Weather</th>
				<th>Wind</th>
				<th>Low Temperature (°C)</th>
				<th>High Temperature (°C)</th>
			</tr>
		</thead>

		<tbody>
			<% @highs_and_lows.each do |date, forecast| %>
				<tr>
					<td><%= date %></td>
					<td><%= forecast[:weather].first["description"] %></td>
					<td><%= forecast[:wind]["speed"] %></td>
					<td><%= forecast[:low] %> °C</td>
					<td><%= forecast[:high] %> °C</td>
				</tr>
			<% end %>
		</tbody>
	</table>
	<br>
	<div>This data was retrieved from the
	<% if @cached %>
		Rails Cache.
	<% else %>
		OpenWeahter API.
	<% end %>
	</div>

	<br>

	<%= link_to 'Back', root_path %>
</div>